<?php

namespace App\DashboardBundle\Repository;

/**
 * RegistryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistryRepository extends \Doctrine\ORM\EntityRepository
{
}
